package com.eminentlabs.mom;
// Generated Jan 10, 2013 10:12:46 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * MomUserTask generated by hbm2java
 */
public class MomUserTask  implements java.io.Serializable {


     private String momtaskid;
     private Integer userid;
     private String task;
     private String type;
     private String tasktime;
     private Date momdate;
     private Integer createdby;
     private Date createdon;
     private Date modifiedon;
          private Integer sino;


    public MomUserTask() {
    }

	
    public MomUserTask(String momtaskid, Integer userid, Date momdate) {
        this.momtaskid = momtaskid;
        this.userid = userid;
        this.momdate = momdate;
    }
    public MomUserTask(String momtaskid, Integer userid, String task,String tasktime, Date momdate, Integer createdby, Date createdon, Date modifiedon) {
       this.momtaskid = momtaskid;
       this.userid = userid;
       this.task = task;
       this.tasktime=tasktime;
       this.momdate = momdate;
       this.createdby = createdby;
       this.createdon = createdon;
       this.modifiedon = modifiedon;
    }
   
    public String getMomtaskid() {
        return this.momtaskid;
    }
    
    public void setMomtaskid(String momtaskid) {
        this.momtaskid = momtaskid;
    }
    public Integer getUserid() {
        return this.userid;
    }
    
    public void setUserid(Integer userid) {
        this.userid = userid;
    }
    public String getTask() {
        return this.task;
    }
    
    public void setTask(String task) {
        this.task = task;
    }
    public String getTasktime() {
        return this.tasktime;
    }
    public void setTasktime(String tasktime) {
        this.tasktime = tasktime;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Date getMomdate() {
        return this.momdate;
    }
    
    public void setMomdate(Date momdate) {
        this.momdate = momdate;
    }
    public Integer getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(Integer createdby) {
        this.createdby = createdby;
    }
    public Date getCreatedon() {
        return this.createdon;
    }
    
    public void setCreatedon(Date createdon) {
        this.createdon = createdon;
    }
    public Date getModifiedon() {
        return this.modifiedon;
    }
    
    public void setModifiedon(Date modifiedon) {
        this.modifiedon = modifiedon;
    }

    public Integer getSino() {
        return sino;
    }

    public void setSino(Integer sino) {
        this.sino = sino;
    }

    @Override
    public String toString() {
        return "MomUserTask{" + "momtaskid=" + momtaskid + ", userid=" + userid + ", task=" + task + ", type=" + type + ", tasktime=" + tasktime + ", momdate=" + momdate + ", createdby=" + createdby + ", createdon=" + createdon + ", modifiedon=" + modifiedon + ", sino=" + sino + '}';
    }

    



}


