package com.eminent.timesheet;
// Generated Nov 1, 2009 6:55:32 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role  implements java.io.Serializable {


     private BigDecimal roleid;
     private String role;
     private Set<Users> userses = new HashSet<Users>(0);

    public Role() {
    }

	
    public Role(BigDecimal roleid) {
        this.roleid = roleid;
    }
    public Role(BigDecimal roleid, String role, Set<Users> userses) {
       this.roleid = roleid;
       this.role = role;
       this.userses = userses;
    }
   
    public BigDecimal getRoleid() {
        return this.roleid;
    }
    
    public void setRoleid(BigDecimal roleid) {
        this.roleid = roleid;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }
    public Set<Users> getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set<Users> userses) {
        this.userses = userses;
    }




}


