package com.eminent.timesheet;
// Generated Nov 13, 2009 12:02:37 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.sql.Timestamp;

/**
 * Timesheet generated by hbm2java
 */
public class Timesheet  implements java.io.Serializable {


     private String timesheetid;
     private Users users;
     private Timestamp requestedon;
     private BigDecimal assignedto;
     private BigDecimal approvalpercentage;
     private String approvalstatus;
     private Timestamp approvedon;
     private String feedback;
     private String appreciation;
     private BigDecimal approvedby;
     private BigDecimal attendance;
     private BigDecimal workingdays;
     private BigDecimal attendenceupdatedby;
     private Timestamp attendenceupdatedon;
     private String attendenceremark;
     private String accountstatus;
     private BigDecimal accountupdatedby;
     private String accountsremarks;
     private Timestamp accountsupdatedon;
     private String accomplishments;
     private String learning;
     private String hardship;
     private String suggestion;
     private String plan;
     private Character appraisalEligibility;
          private BigDecimal hoursInOffice;
     private BigDecimal hoursInMeeting;
      private String wonAccounts;
     private String metDecisionMaker;
     private String identityDecisionMaker;
     private String metInfluencer;
     private String identityInfluencer;
     private Set<Timesheetinfo> timesheetcommentses = new HashSet<Timesheetinfo>(0);

    public Timesheet() {
    }

	
    public Timesheet(String timesheetid) {
        this.timesheetid = timesheetid;
    }
    public Timesheet(String timesheetid, Users users, Timestamp requestedon, BigDecimal assignedto, BigDecimal approvalpercentage, String approvalstatus, Timestamp approvedon, String feedback, String appreciation, BigDecimal approvedby, BigDecimal attendance, BigDecimal workingdays, BigDecimal attendenceupdatedby, Timestamp attendenceupdatedon, String attendenceremark, String accountstatus, BigDecimal accountupdatedby, String accountsremarks, Timestamp accountsupdatedon, String accomplishments, String learning,String hardship,String suggestion, String plan,Character appraisalEligibility, Set<Timesheetinfo> timesheetcommentses) {
       this.timesheetid = timesheetid;
       this.users = users;
       this.requestedon = requestedon;
       this.assignedto = assignedto;
       this.approvalpercentage = approvalpercentage;
       this.approvalstatus  =   approvalstatus;
       this.approvedon = approvedon;
       this.feedback = feedback;
       this.appreciation = appreciation;
       this.approvedby = approvedby;
       this.attendance = attendance;
       this.workingdays = workingdays;
       this.attendenceupdatedby = attendenceupdatedby;
       this.attendenceupdatedon = attendenceupdatedon;
       this.attendenceremark = attendenceremark;
       this.accountstatus = accountstatus;
       this.accountupdatedby = accountupdatedby;       this.accountsremarks = accountsremarks;
       this.accountsupdatedon = accountsupdatedon;
       this.accomplishments = accomplishments;
       this.learning = learning;
       this.hardship = hardship;
       this.suggestion = suggestion;
       this.plan    =   plan;
       this.appraisalEligibility    =   appraisalEligibility;
       this.timesheetcommentses = timesheetcommentses;
    }
   
    public String getTimesheetid() {
        return this.timesheetid;
    }
    
    public void setTimesheetid(String timesheetid) {
        this.timesheetid = timesheetid;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Date getRequestedon() {
        return this.requestedon;
    }
    
    public void setRequestedon(Timestamp requestedon) {
        this.requestedon = requestedon;
    }
    public BigDecimal getAssignedto() {
        return this.assignedto;
    }
    
    public void setAssignedto(BigDecimal assignedto) {
        this.assignedto = assignedto;
    }
    public BigDecimal getApprovalpercentage() {
        return this.approvalpercentage;
    }
    
    public void setApprovalpercentage(BigDecimal approvalpercentage) {
        this.approvalpercentage = approvalpercentage;
    }
    public String getApprovalstatus() {
        return this.approvalstatus;
    }

    public void setApprovalstatus(String approvalstatus) {
        this.approvalstatus = approvalstatus;
    }
    public Date getApprovedon() {
        return this.approvedon;
    }
    
    public void setApprovedon(Timestamp approvedon) {
        this.approvedon = approvedon;
    }
    public String getFeedback() {
        return this.feedback;
    }
    
    public void setFeedback(String feedback) {
        this.feedback = feedback;
    }
    public String getAppreciation() {
        return this.appreciation;
    }
    
    public void setAppreciation(String appreciation) {
        this.appreciation = appreciation;
    }
    public BigDecimal getApprovedby() {
        return this.approvedby;
    }
    
    public void setApprovedby(BigDecimal approvedby) {
        this.approvedby = approvedby;
    }
    public BigDecimal getAttendance() {
        return this.attendance;
    }
    
    public void setAttendance(BigDecimal attendance) {
        this.attendance = attendance;
    }
    public BigDecimal getWorkingdays() {
        return this.workingdays;
    }
    
    public void setWorkingdays(BigDecimal workingdays) {
        this.workingdays = workingdays;
    }
    public BigDecimal getAttendenceupdatedby() {
        return this.attendenceupdatedby;
    }
    
    public void setAttendenceupdatedby(BigDecimal attendenceupdatedby) {
        this.attendenceupdatedby = attendenceupdatedby;
    }
    public Date getAttendenceupdatedon() {
        return this.attendenceupdatedon;
    }
    
    public void setAttendenceupdatedon(Timestamp attendenceupdatedon) {
        this.attendenceupdatedon = attendenceupdatedon;
    }
    public String getAttendenceremark() {
        return this.attendenceremark;
    }
    
    public void setAttendenceremark(String attendenceremark) {
        this.attendenceremark = attendenceremark;
    }
    public String getAccountstatus() {
        return this.accountstatus;
    }
    
    public void setAccountstatus(String accountstatus) {
        this.accountstatus = accountstatus;
    }
    public BigDecimal getAccountupdatedby() {
        return this.accountupdatedby;
    }
    
    public void setAccountupdatedby(BigDecimal accountupdatedby) {
        this.accountupdatedby = accountupdatedby;
    }
    public String getAccountsremarks() {
        return this.accountsremarks;
    }
    
    public void setAccountsremarks(String accountsremarks) {
        this.accountsremarks = accountsremarks;
    }
    public Date getAccountsupdatedon() {
        return this.accountsupdatedon;
    }
    
    public void setAccountsupdatedon(Timestamp accountsupdatedon) {
        this.accountsupdatedon = accountsupdatedon;
    }
    public String getAccomplishments() {
        return this.accomplishments;
    }
    
    public void setAccomplishments(String accomplishments) {
        this.accomplishments = accomplishments;
    }
    public String getLearning() {
        return this.learning;
    }
    
    public void setLearning(String learning) {
        this.learning = learning;
    }
    public String getHardship() {
        return this.hardship;
    }

    public void setHardship(String hardship) {
        this.hardship = hardship;
    }
    public String getSuggestion() {
        return this.suggestion;
    }

    public void setSuggestion(String suggestion) {
        this.suggestion = suggestion;
    }
    public String getPlan() {
        return this.plan;
    }

    public void setPlan(String plan) {
        this.plan = plan;
    }
    public Character getAppraisalEligibility() {
        return this.appraisalEligibility;
    }

    public void setAppraisalEligibility(Character appraisalEligibility) {
        this.appraisalEligibility = appraisalEligibility;
    }
    public Set<Timesheetinfo> getTimesheetcommentses() {
        return this.timesheetcommentses;
    }
    
    public void setTimesheetcommentses(Set<Timesheetinfo> timesheetcommentses) {
        this.timesheetcommentses = timesheetcommentses;
    }

    public BigDecimal getHoursInOffice() {
        return hoursInOffice;
    }

    public void setHoursInOffice(BigDecimal hoursInOffice) {
        this.hoursInOffice = hoursInOffice;
    }

    public BigDecimal getHoursInMeeting() {
        return hoursInMeeting;
    }

    public void setHoursInMeeting(BigDecimal hoursInMeeting) {
        this.hoursInMeeting = hoursInMeeting;
    }

    public String getWonAccounts() {
        return wonAccounts;
    }

    public void setWonAccounts(String wonAccounts) {
        this.wonAccounts = wonAccounts;
    }

    public String getMetDecisionMaker() {
        return metDecisionMaker;
    }

    public void setMetDecisionMaker(String metDecisionMaker) {
        this.metDecisionMaker = metDecisionMaker;
    }

    public String getIdentityDecisionMaker() {
        return identityDecisionMaker;
    }

    public void setIdentityDecisionMaker(String identityDecisionMaker) {
        this.identityDecisionMaker = identityDecisionMaker;
    }

    public String getMetInfluencer() {
        return metInfluencer;
    }

    public void setMetInfluencer(String metInfluencer) {
        this.metInfluencer = metInfluencer;
    }

    public String getIdentityInfluencer() {
        return identityInfluencer;
    }

    public void setIdentityInfluencer(String identityInfluencer) {
        this.identityInfluencer = identityInfluencer;
    }




}


