package com.eminent.timesheet;
// Generated Nov 13, 2009 12:02:37 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.sql.Timestamp;

/**
 * Timesheetinfo generated by hbm2java
 */
public class Timesheetinfo  implements java.io.Serializable {


     private long infoid;
     private Users usersByInfoto;
     private Users usersByInfoby;
     private Timesheet timesheet;
     private Timestamp infoaddedon;
     private String info;

    public Timesheetinfo() {
    }

	
    public Timesheetinfo(long infoid) {
        this.infoid = infoid;
    }
    public Timesheetinfo(long infoid, Users usersByInfoto, Users usersByInfoby, Timesheet timesheet, Timestamp infoaddedon, String info) {
       this.infoid = infoid;
       this.usersByInfoto = usersByInfoto;
       this.usersByInfoby = usersByInfoby;
       this.timesheet = timesheet;
       this.infoaddedon = infoaddedon;
       this.info = info;
    }
   
    public long getInfoid() {
        return this.infoid;
    }
    
    public void setInfoid(long infoid) {
        this.infoid = infoid;
    }
    public Users getUsersByInfoto() {
        return this.usersByInfoto;
    }
    
    public void setUsersByInfoto(Users usersByInfoto) {
        this.usersByInfoto = usersByInfoto;
    }
    public Users getUsersByInfoby() {
        return this.usersByInfoby;
    }
    
    public void setUsersByInfoby(Users usersByInfoby) {
        this.usersByInfoby = usersByInfoby;
    }
    public Timesheet getTimesheet() {
        return this.timesheet;
    }
    
    public void setTimesheet(Timesheet timesheet) {
        this.timesheet = timesheet;
    }
    public Date getInfoaddedon() {
        return this.infoaddedon;
    }
    
    public void setInfoaddedon(Timestamp infoaddedon) {
        this.infoaddedon = infoaddedon;
    }
    public String getInfo() {
        return this.info;
    }
    
    public void setInfo(String info) {
        this.info = info;
    }




}


