package com.eminent.timesheet;
// Generated Nov 13, 2009 12:02:37 PM by Hibernate Tools 3.2.1.GA



import java.util.HashSet;
import java.util.Set;
import com.eminent.issue.Issue;
import com.eminent.leaveUtil.Leave;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private int userid;
     private Role role;
     private String firstname;
     private String lastname;
     private String password;
     private String email;
     private String company;
     private String secret;
     private String answer;
     private String phone;
     private String mobile;
     private String team;
     private String mobileoperator;
     private int value;
     private Set<Timesheetinfo> timesheetcommentsesForCommentedby = new HashSet<Timesheetinfo>(0);
     private Set<Timesheet> timesheets = new HashSet<Timesheet>(0);
     private Set<Timesheetinfo> timesheetcommentsesForCommentedto = new HashSet<Timesheetinfo>(0);
     private Set<Issue> issueCreatedby  =   new HashSet<Issue>(0);
     private Set<Issue> issueAssignedto  =   new HashSet<Issue>(0);
     private Set<Leave> leaveRequests = new HashSet<Leave>(0);

    public Users() {
    }

	
    public Users(int userid, Role role, String firstname, String lastname, String password, String email, String company, String secret, String answer, String mobile, String mobileoperator) {
        this.userid = userid;
        this.role = role;
        this.firstname = firstname;
        this.lastname = lastname;
        this.password = password;
        this.email = email;
        this.company = company;
        this.secret = secret;
        this.answer = answer;
        this.mobile = mobile;
        this.mobileoperator = mobileoperator;
    }
    public Users(int userid, Role role, String firstname, String lastname, String password, String email, String company, String secret, String answer, String phone, String mobile, String team, String mobileoperator, int value, Set<Timesheetinfo> timesheetcommentsesForCommentedby, Set<Timesheet> timesheets, Set<Timesheetinfo> timesheetcommentsesForCommentedto,Set<Issue> issueCreatedby ,Set<Issue> issueAssignedto) {
       this.userid = userid;
       this.role = role;
       this.firstname = firstname;
       this.lastname = lastname;
       this.password = password;
       this.email = email;
       this.company = company;
       this.secret = secret;
       this.answer = answer;
       this.phone = phone;
       this.mobile = mobile;
       this.team = team;
       this.mobileoperator = mobileoperator;
       this.value = value;
       this.timesheetcommentsesForCommentedby = timesheetcommentsesForCommentedby;
       this.timesheets = timesheets;
       this.timesheetcommentsesForCommentedto = timesheetcommentsesForCommentedto;
       this.issueAssignedto = issueAssignedto;
       this.issueCreatedby  = issueCreatedby;
    }
   
    public int getUserid() {
        return this.userid;
    }
    
    public void setUserid(int userid) {
        this.userid = userid;
    }
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }
    public String getSecret() {
        return this.secret;
    }
    
    public void setSecret(String secret) {
        this.secret = secret;
    }
    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getTeam() {
        return this.team;
    }
    
    public void setTeam(String team) {
        this.team = team;
    }
    public String getMobileoperator() {
        return this.mobileoperator;
    }
    
    public void setMobileoperator(String mobileoperator) {
        this.mobileoperator = mobileoperator;
    }
    public int getValue() {
        return this.value;
    }
    
    public void setValue(int value) {
        this.value = value;
    }
    public Set<Timesheetinfo> getTimesheetcommentsesForCommentedby() {
        return this.timesheetcommentsesForCommentedby;
    }
    
    public void setTimesheetcommentsesForCommentedby(Set<Timesheetinfo> timesheetcommentsesForCommentedby) {
        this.timesheetcommentsesForCommentedby = timesheetcommentsesForCommentedby;
    }
    public Set<Timesheet> getTimesheets() {
        return this.timesheets;
    }
    
    public void setTimesheets(Set<Timesheet> timesheets) {
        this.timesheets = timesheets;
    }
    public Set<Timesheetinfo> getTimesheetcommentsesForCommentedto() {
        return this.timesheetcommentsesForCommentedto;
    }
    
    public void setTimesheetcommentsesForCommentedto(Set<Timesheetinfo> timesheetcommentsesForCommentedto) {
        this.timesheetcommentsesForCommentedto = timesheetcommentsesForCommentedto;
    }
    public Set<Issue> getIssueCreatedby() {
        return this.issueCreatedby;
    }

    public void setIssueCreatedby(Set<Issue> issueCreatedby) {
        this.issueCreatedby = issueCreatedby;
    }
    public Set<Issue> getIssueAssignedto() {
        return this.issueAssignedto;
    }

    public void setIssueAssignedto(Set<Issue> issueAssignedto) {
        this.issueAssignedto = issueAssignedto;
    }



}


