package com.eminentlabs.appraisal;
// Generated Dec 17, 2011 10:34:40 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * ErmAppraisalStatus generated by hbm2java
 */
public class ErmAppraisalStatus  implements java.io.Serializable {


     private Integer statusId;
     private String status;
     private Set<ErmAppraisal> ermAppraisals = new HashSet<ErmAppraisal>(0);

    public ErmAppraisalStatus() {
    }

	
    public ErmAppraisalStatus(Integer statusId) {
        this.statusId = statusId;
    }
    public ErmAppraisalStatus(Integer statusId, String status, Set<ErmAppraisal> ermAppraisals) {
       this.statusId = statusId;
       this.status = status;
       this.ermAppraisals = ermAppraisals;
    }
   
    public Integer getStatusId() {
        return this.statusId;
    }
    
    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set<ErmAppraisal> getErmAppraisals() {
        return this.ermAppraisals;
    }
    
    public void setErmAppraisals(Set<ErmAppraisal> ermAppraisals) {
        this.ermAppraisals = ermAppraisals;
    }




}


