package com.eminentlabs.appraisal;
// Generated Jan 25, 2012 2:31:06 PM by Hibernate Tools 3.2.1.GA

/**
 * ErmAppraisalAchievement generated by hbm2java
 */
public class ErmAppraisalAchievement  implements java.io.Serializable {


     private Integer achievementId;
     private String issueId;
     private Integer appraisalId;
     private String type;

    public ErmAppraisalAchievement() {
    }

	
    public ErmAppraisalAchievement(Integer achievementId) {
        this.achievementId = achievementId;
    }
    public ErmAppraisalAchievement(Integer achievementId, String issueId, Integer appraisalId, String type) {
       this.achievementId = achievementId;
       this.issueId = issueId;
       this.appraisalId = appraisalId;
       this.type = type;
    }
   
    public Integer getAchievementId() {
        return this.achievementId;
    }
    
    public void setAchievementId(Integer achievementId) {
        this.achievementId = achievementId;
    }
    public String getIssueId() {
        return this.issueId;
    }
    
    public void setIssueId(String issueId) {
        this.issueId = issueId;
    }
    public Integer getAppraisalId() {
        return this.appraisalId;
    }
    
    public void setAppraisalId(Integer appraisalId) {
        this.appraisalId = appraisalId;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }




}


