package com.eminentlabs.appraisal;
// Generated Dec 17, 2011 10:34:40 AM by Hibernate Tools 3.2.1.GA

/**
 * ErmAppraisalStatusFlow generated by hbm2java
 */
public class ErmAppraisalStatusFlow  implements java.io.Serializable {


     private Integer statusFlowId;
     private Integer statusMasterId;
     private Integer statusSubId;

    public ErmAppraisalStatusFlow() {
    }

	
    public ErmAppraisalStatusFlow(Integer statusFlowId) {
        this.statusFlowId = statusFlowId;
    }
    public ErmAppraisalStatusFlow(Integer statusFlowId, Integer statusMasterId, Integer statusSubId) {
       this.statusFlowId = statusFlowId;
       this.statusMasterId = statusMasterId;
       this.statusSubId = statusSubId;
    }
   
    public Integer getStatusFlowId() {
        return this.statusFlowId;
    }
    
    public void setStatusFlowId(Integer statusFlowId) {
        this.statusFlowId = statusFlowId;
    }
    public Integer getStatusMasterId() {
        return this.statusMasterId;
    }
    
    public void setStatusMasterId(Integer statusMasterId) {
        this.statusMasterId = statusMasterId;
    }
    public Integer getStatusSubId() {
        return this.statusSubId;
    }
    
    public void setStatusSubId(Integer statusSubId) {
        this.statusSubId = statusSubId;
    }




}


