package com.eminent.tqm;
// Generated 16 Mar, 2010 7:45:03 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import com.eminent.timesheet.Users;

/**
 * TqmTestcaseexecutionplan generated by hbm2java
 */
public class TqmTestcaseexecutionplan  implements java.io.Serializable {


     private int tepid;
     private String planname;
     private TqmTestcaseplanstatus tqmTestcaseplanstatus;
     private Date plannedstart;
     private Date plannedend;
     private Date actualstart;
     private Date actualend;
     private Integer pid;
     private String buildno;
     private String mainprocess;
     private String subprocess;
     private String scenario;
     private String variant;
     private Users qualitymanager;
     private Users createdby;
     private Date createdon;
     private Date modifiedon;


    public TqmTestcaseexecutionplan() {
    }

	
    public TqmTestcaseexecutionplan(int tepid) {
        this.tepid = tepid;
    }
    public TqmTestcaseexecutionplan(int tepid, String planname, TqmTestcaseplanstatus tqmTestcaseplanstatus, Date plannedstart, Date plannedend, Date actualstart, Date actualend, Integer pid, String buildno,String mainprocess,String subprocess,String scenario,String variant,Users qualitymanager, Users createdby, Date createdon, Date modifiedon, Set tqmTestcaseexecutions,Set tqmModuleplans) {
       this.tepid = tepid;
       this.planname    =   planname;
       this.tqmTestcaseplanstatus = tqmTestcaseplanstatus;
       this.plannedstart = plannedstart;
       this.plannedend = plannedend;
       this.actualstart = actualstart;
       this.actualend = actualend;
       this.pid = pid;
       this.buildno = buildno;
       this.mainprocess=mainprocess;
       this.subprocess=subprocess;
       this.scenario=scenario;
       this.variant=variant;
       this.qualitymanager  =   qualitymanager;
       this.createdby = createdby;
       this.createdon = createdon;
       this.modifiedon = modifiedon;

    }
   
    public int getTepid() {
        return this.tepid;
    }
    
    public void setTepid(int tepid) {
        this.tepid = tepid;
    }
    public String getPlanname() {
        return this.planname;
    }
    public void setPlanname(String planname) {
        this.planname = planname;
    }
    public TqmTestcaseplanstatus getTqmTestcaseplanstatus() {
        return this.tqmTestcaseplanstatus;
    }
    
    public void setTqmTestcaseplanstatus(TqmTestcaseplanstatus tqmTestcaseplanstatus) {
        this.tqmTestcaseplanstatus = tqmTestcaseplanstatus;
    }
    public Date getPlannedstart() {
        return this.plannedstart;
    }
    
    public void setPlannedstart(Date plannedstart) {
        this.plannedstart = plannedstart;
    }
    public Date getPlannedend() {
        return this.plannedend;
    }
    
    public void setPlannedend(Date plannedend) {
        this.plannedend = plannedend;
    }
    public Date getActualstart() {
        return this.actualstart;
    }
    
    public void setActualstart(Date actualstart) {
        this.actualstart = actualstart;
    }
    public Date getActualend() {
        return this.actualend;
    }
    
    public void setActualend(Date actualend) {
        this.actualend = actualend;
    }
    public Integer getPid() {
        return this.pid;
    }
    
    public void setPid(Integer pid) {
        this.pid = pid;
    }
    public String getBuildno() {
        return this.buildno;
    }
    
    public void setBuildno(String buildno) {
        this.buildno = buildno;
    }
    public String getMainprocess() {
        return this.mainprocess;
    }
    public void setMainprocess(String mainprocess) {
        this.mainprocess = mainprocess;
    }
    public String getSubprocess() {
        return this.subprocess;
    }

    public void setSubprocess(String subprocess) {
        this.subprocess = subprocess;
    }
    public String getScenario() {
        return this.scenario;
    }

    public void setScenario(String scenario) {
        this.scenario = scenario;
    }
    public String getVariant() {
        return this.variant;
    }

    public void setVariant(String variant) {
        this.variant = variant;
    }
    public Users getQualitymanager() {
        return this.qualitymanager;
    }

    public void setQualitymanager(Users qualitymanager) {
        this.qualitymanager = qualitymanager;
    }
    public Users getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(Users createdby) {
        this.createdby = createdby;
    }
    public Date getCreatedon() {
        return this.createdon;
    }
    
    public void setCreatedon(Date createdon) {
        this.createdon = createdon;
    }
    public Date getModifiedon() {
        return this.modifiedon;
    }
    
    public void setModifiedon(Date modifiedon) {
        this.modifiedon = modifiedon;
    }
    /*
    public Set getTqmTestcaseexecutions() {
        return this.tqmTestcaseexecutions;
    }
    
    public void setTqmTestcaseexecutions(Set tqmTestcaseexecutions) {
        this.tqmTestcaseexecutions = tqmTestcaseexecutions;
    }
     public Set getTqmModuleplans() {
        return this.tqmModuleplans;
    }

    public void setTqmModuleplans(Set tqmModuleplans) {
        this.tqmModuleplans = tqmModuleplans;
    }
-->*/


}


