package com.eminent.tqm;
// Generated 16 Mar, 2010 7:45:03 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * TqmTestcaseexecutionresult generated by hbm2java
 */
public class TqmTestcaseexecutionresult  implements java.io.Serializable {


     private int terid;
     private TqmTestcaseexecution tqmTestcaseexecution;
     private Integer statusid;
     private TqmPtcm ptcid;
     private String comments;
     private Integer commentedby;
     private Integer commentedto;
     private Date commentedon;
     private Date duedate;
    public TqmTestcaseexecutionresult() {
    }

	
    public TqmTestcaseexecutionresult(int terid) {
        this.terid = terid;
    }
    public TqmTestcaseexecutionresult(String comments, Integer commentedby, Date commentedon,Integer statusid) {

       this.comments = comments;
       this.commentedby = commentedby;
       this.commentedon = commentedon;
       this.statusid = statusid;

    }
    public TqmTestcaseexecutionresult(int terid, TqmTestcaseexecution tqmTestcaseexecution, Integer statusid, TqmPtcm ptcid, String comments, Integer commentedby, Integer commentedto, Date commentedon,Date duedate) {
       this.terid = terid;
       this.tqmTestcaseexecution = tqmTestcaseexecution;
       this.ptcid = ptcid;
       this.statusid = statusid;
       this.comments = comments;
       this.commentedby = commentedby;
       this.commentedto = commentedto;
       this.commentedon = commentedon;
       this.duedate     = duedate;
    }
   
    public int getTerid() {
        return this.terid;
    }
    
    public void setTerid(int terid) {
        this.terid = terid;
    }
    public TqmTestcaseexecution getTqmTestcaseexecution() {
        return this.tqmTestcaseexecution;
    }
    
    public void setTqmTestcaseexecution(TqmTestcaseexecution tqmTestcaseexecution) {
        this.tqmTestcaseexecution = tqmTestcaseexecution;
    }
     public Integer getStatusid() {
        return this.statusid;
    }

    public void setStatusid(Integer statusid) {
        this.statusid = statusid;
    }
    public TqmPtcm getPtcid() {
        return this.ptcid;
    }

    public void setPtcid(TqmPtcm ptcid) {
        this.ptcid = ptcid;
    }
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }
    public Integer getCommentedby() {
        return this.commentedby;
    }
    
    public void setCommentedby(Integer commentedby) {
        this.commentedby = commentedby;
    }
    public void setCommentedto(int commentedto){
        this.commentedto=commentedto;
    }
    public Integer getCommentedto(){
        return commentedto;
    }
    public Date getCommentedon() {
        return this.commentedon;
    }
    
    public void setCommentedon(Date commentedon) {
        this.commentedon = commentedon;
    }
    public Date getDuedate() {
        return this.duedate;
    }

    public void setDuedate(Date duedate) {
        this.duedate = duedate;
    }



}


