package com.eminent.tqm;
// Generated 16 Mar, 2010 7:45:03 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import com.eminent.timesheet.Users;

/**
 * TqmTestcaseexecution generated by hbm2java
 */
public class TqmTestcaseexecution  implements java.io.Serializable {


     private int tceid;
     private TqmTestcaseexecutionplan tqmTestcaseexecutionplan;
     private int statusid;
     private TqmPtcm ptcid;
     private Users createdby;
     private Users assignedto;
     private Date createdon;
     private Date modifiedon;
     private Date duedate;
     private String issuereference;
     private int testorder;

    public TqmTestcaseexecution() {
    }

	
    public TqmTestcaseexecution(int tceid) {
        this.tceid = tceid;
    }
    public TqmTestcaseexecution(int tceid, TqmTestcaseexecutionplan tqmTestcaseexecutionplan, int statusid, TqmPtcm ptcid, Users createdby, Users assignedto, Date createdon, Date modifiedon, Date duedate, String issuereference, int testorder) {
       this.tceid = tceid;
       this.tqmTestcaseexecutionplan = tqmTestcaseexecutionplan;
       this.statusid = statusid;
       this.ptcid = ptcid;
       this.createdby = createdby;
       this.assignedto = assignedto;
       this.createdon = createdon;
       this.modifiedon = modifiedon;
       this.duedate    =    duedate;
       this.issuereference  = issuereference;
       this.testorder  = testorder;
    }
   
    public int getTceid() {
        return this.tceid;
    }
    
    public void setTceid(int tceid) {
        this.tceid = tceid;
    }
    public TqmTestcaseexecutionplan getTqmTestcaseexecutionplan() {
        return this.tqmTestcaseexecutionplan;
    }
    
    public void setTqmTestcaseexecutionplan(TqmTestcaseexecutionplan tqmTestcaseexecutionplan) {
        this.tqmTestcaseexecutionplan = tqmTestcaseexecutionplan;
    }
    public int getStatusid() {
        return this.statusid;
    }
    
    public void setStatusid(int statusid) {
        this.statusid = statusid;
    }
    public TqmPtcm getPtcid() {
        return this.ptcid;
    }
    
    public void setPtcid(TqmPtcm ptcid) {
        this.ptcid = ptcid;
    }
    public Users getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(Users createdby) {
        this.createdby = createdby;
    }
    public Users getAssignedto() {
        return this.assignedto;
    }
    
    public void setAssignedto(Users assignedto) {
        this.assignedto = assignedto;
    }
    public Date getCreatedon() {
        return this.createdon;
    }
    
    public void setCreatedon(Date createdon) {
        this.createdon = createdon;
    }
    public Date getModifiedon() {
        return this.modifiedon;
    }
    
    public void setModifiedon(Date modifiedon) {
        this.modifiedon = modifiedon;
    }
    public Date getDuedate() {
        return this.duedate;
    }

    public void setDuedate(Date duedate) {
        this.duedate = duedate;
    }
    public int getTestorder() {
        return this.testorder;
    }
    public void setTestorder(int testorder) {
        this.testorder = testorder;
    }
     public String getIssuereference() {
        return this.issuereference;
    }

    public void setIssuereference(String issuereference) {
        this.issuereference = issuereference;
    }



}


