package com.eminent.tqm;
// Generated 16 Mar, 2010 7:45:03 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TqmTestcaseplanstatus generated by hbm2java
 */
public class TqmTestcaseplanstatus  implements java.io.Serializable {


     private short statusid;
     private String status;
    

    public TqmTestcaseplanstatus() {
    }

	
    public TqmTestcaseplanstatus(short statusid) {
        this.statusid = statusid;
    }
    public TqmTestcaseplanstatus(short statusid, String status) {
       this.statusid = statusid;
       this.status = status;
     
    }
   
    public short getStatusid() {
        return this.statusid;
    }
    
    public void setStatusid(short statusid) {
        this.statusid = statusid;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
   
}


