
CREATE OR REPLACE FORCE VIEW  "MAXCOMMENTDATE" ("ISSUEID", "COMMENTDATE") AS 
  select issueid,Max(comment_date) as commentdate from issuecomments where COMMENTedBy!=commentedTo group by issueid
/

CREATE OR REPLACE FORCE VIEW  "LASTASSIGNEENAME" ("ISSUEID", "FIRSTNAME ||' '|| LASTNAME", "COMMENT_DATE") AS 
  select distinct(ic.ISSUEID), FIRSTNAME ||' '|| SUBSTR(LASTNAME,1,1),to_char(comment_date,'DD-Mon-YYYY HH:mi:ss') from issuecomments ic,maxcommentdate m,users u where to_char(u.userid)=ic.commentedby and comment_date=m.COMMENTDATE and ic.issueid=m.issueid
/
CREATE TABLE  "TIMESHEET_ISSUE" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"ISSUEID" VARCHAR2(12) NOT NULL ENABLE, 
	"TIMESHEETID" VARCHAR2(25) NOT NULL ENABLE, 
	"WORKSTATUS" NUMBER(1,0) NOT NULL ENABLE, 
	 CONSTRAINT "TIMESHEET_ISSUE_PK" PRIMARY KEY ("ID") ENABLE, 
	 CONSTRAINT "TIMESHEET_ISSUE_CON" UNIQUE ("TIMESHEETID", "ISSUEID") ENABLE, 
	 CONSTRAINT "TIMESHEET_ISSUE_FK" FOREIGN KEY ("TIMESHEETID")
	  REFERENCES  "TIMESHEET" ("TIMESHEETID") ENABLE
   )
/
CREATE SEQUENCE   "TIMESHEET_ISSUE_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE
/
CREATE OR REPLACE TRIGGER  "BI_TIMESHEET_ISSUE" 
  before insert on "TIMESHEET_ISSUE"               
  for each row  
begin   
    select "TIMESHEET_ISSUE_SEQ".nextval into :NEW.ID from dual; 
end; 

/
ALTER TRIGGER  "BI_TIMESHEET_ISSUE" ENABLE
/
