CREATE TABLE  "MODULETARGET" 
   (	"TARGETID" NUMBER NOT NULL ENABLE, 
	"MONTH" CHAR(20) NOT NULL ENABLE, 
	"TARGET" NUMBER, 
	"MODULEID" NUMBER, 
	 CONSTRAINT "MODULETARGET_PK" PRIMARY KEY ("TARGETID") ENABLE, 
	 CONSTRAINT "MODULETARGET_CON" UNIQUE ("MODULEID", "MONTH") ENABLE
   )
/
 CREATE SEQUENCE   "MODULETARGET_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE
/
CREATE OR REPLACE TRIGGER  "BI_MODULETARGET" 
  before insert on "MODULETARGET"               
  for each row  
begin   
    select "MODULETARGET_SEQ".nextval into :NEW.TARGETID from dual; 
end; 

/
ALTER TRIGGER  "BI_MODULETARGET" ENABLE
/
