CREATE TABLE  "USERS_PERFORMANCE" 
   (	"ID" NUMBER, 
	"USERID" NUMBER NOT NULL ENABLE, 
	"TASKS" VARCHAR2(4000), 
	"STARTDATE" DATE NOT NULL ENABLE, 
	"ENDDATE" DATE NOT NULL ENABLE, 
	"CREATEDON" TIMESTAMP (6) NOT NULL ENABLE, 
	"EVALUATION_DATE" DATE NOT NULL ENABLE, 
	"PERFORMANCETYPE" VARCHAR2(4000) NOT NULL ENABLE, 
	 CONSTRAINT "USERS_PERFORMANCE_PK" PRIMARY KEY ("ID") ENABLE, 
	 CONSTRAINT "USERS_PERFORMANCE_CONS" UNIQUE ("USERID", "STARTDATE", "ENDDATE") ENABLE
   )
/

CREATE OR REPLACE TRIGGER  "BI_USERS_PERFORMANCE" 
  before insert on "USERS_PERFORMANCE"               
  for each row  
begin   
    select "USERS_PERFORMANCE_SEQ".nextval into :NEW.ID from dual; 
end; 

/
ALTER TRIGGER  "BI_USERS_PERFORMANCE" ENABLE
/
CREATE TABLE  "PROJECT_PLANNED_ISSUE" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"PID" NUMBER NOT NULL ENABLE, 
	"ISSUEID" VARCHAR2(12) NOT NULL ENABLE, 
	"PLANNEDBY" NUMBER NOT NULL ENABLE, 
	"PLANNEDON" TIMESTAMP (6) NOT NULL ENABLE, 
	"STATUS" VARCHAR2(4000) NOT NULL ENABLE, 
	"MODIFIEDON" TIMESTAMP (6) NOT NULL ENABLE, 
	"WEEKYEAR" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "PROJECT_PLANNED_ISSUE_PK" PRIMARY KEY ("ID") ENABLE, 
	 CONSTRAINT "PROJECT_PLANNED_ISSUE_CON" UNIQUE ("PID", "ISSUEID", "WEEKYEAR") ENABLE
   )
/

CREATE OR REPLACE TRIGGER  "BI_PROJECT_PLANNED_ISSUE" 
  before insert on "PROJECT_PLANNED_ISSUE"               
  for each row  
begin   
    select "PROJECTPLANISSUE_SEQ".nextval into :NEW.ID from dual; 
end; 

/
ALTER TRIGGER  "BI_PROJECT_PLANNED_ISSUE" ENABLE
/

CREATE SEQUENCE   "PROJECTPLANISSUE_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE
/
CREATE SEQUENCE   "USERS_PERFORMANCE_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE
/