ALTER TABLE ISSUE MODIFY FEEDBACK  VARCHAR2(210);


ALTER TABLE USERS MODIFY EMAIL NOT NULL;
ALTER TABLE USERS MODIFY FIRSTNAME NOT NULL;
ALTER TABLE USERS MODIFY LASTNAME NOT NULL;
ALTER TABLE USERS MODIFY PASSWORD NOT NULL;
ALTER TABLE USERS MODIFY SECRET NOT NULL;
ALTER TABLE USERS MODIFY ANSWER NOT NULL;
ALTER TABLE USERS MODIFY COMPANY NOT NULL;
ALTER TABLE USERS MODIFY PHONE NOT NULL;
ALTER TABLE USERS MODIFY MOBILE NOT NULL;
ALTER TABLE USERS MODIFY MOBILEOPERATOR NOT NULL;


