CREATE TABLE  "APM_MODULE_ATTACHMENT" 
   (	"ID" NUMBER, 
	"MODULEID" NUMBER NOT NULL ENABLE, 
	"FILENAME" VARCHAR2(100) NOT NULL ENABLE, 
	"ATTACHEDDATE" TIMESTAMP (6) NOT NULL ENABLE, 
	"OWNER" NUMBER NOT NULL ENABLE, 
	"PROJECTID" NUMBER, 
	 CONSTRAINT "MODULEATTACHMENT_PK" PRIMARY KEY ("ID") ENABLE
   )
/
 CREATE SEQUENCE   "MODULEATTACHMENT_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER  NOCYCLE
/
CREATE OR REPLACE TRIGGER  "BI_MODULEATTACHMENT" 
  before insert on "APM_MODULE_ATTACHMENT"               
  for each row  
begin   
    select "MODULEATTACHMENT_SEQ".nextval into :NEW.ID from dual; 
end; 

/
ALTER TRIGGER  "BI_MODULEATTACHMENT" ENABLE
/
