CREATE TABLE  "PM_PERFORMANCE" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"STARTDATE" DATE NOT NULL ENABLE, 
	"ENDDATE" DATE NOT NULL ENABLE, 
	"PID" NUMBER NOT NULL ENABLE, 
	"PMID" NUMBER NOT NULL ENABLE, 
	"CREATEDON" TIMESTAMP (6) NOT NULL ENABLE, 
	 CONSTRAINT "PM_PERFORMANCE_PK" PRIMARY KEY ("ID") ENABLE, 
	 CONSTRAINT "PM_PERFORMANCE_CONS" UNIQUE ("STARTDATE", "ENDDATE") ENABLE
   )
/

CREATE OR REPLACE TRIGGER  "BI_PM_PERFORMANCE" 
  before insert on "PM_PERFORMANCE"               
  for each row  
begin   
    select "PM_PERFORMANCE_SEQ".nextval into :NEW.ID from dual; 
end; 

/
CREATE SEQUENCE   "PM_PERFORMANCE_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE
/

ALTER TRIGGER  "BI_PM_PERFORMANCE" ENABLE
/
CREATE TABLE  "APM_WRM_PLAN" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"WRMDAY" DATE NOT NULL ENABLE, 
	"PLANNEDON" TIMESTAMP (6) NOT NULL ENABLE, 
	"PLANNEDBY" NUMBER NOT NULL ENABLE, 
	"PID" NUMBER NOT NULL ENABLE, 
	"ISSUEID" VARCHAR2(20) NOT NULL ENABLE, 
	"COMMENTS" VARCHAR2(250), 
	"STATUS" VARCHAR2(10), 
	 CONSTRAINT "APM_WRM_PLAN_PK" PRIMARY KEY ("ID") ENABLE, 
	 CONSTRAINT "APM_WRM_PLAN_CON" UNIQUE ("WRMDAY", "PID", "ISSUEID") ENABLE
   )
/
 CREATE SEQUENCE   "APM_WRM_PLAN_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE
/
CREATE OR REPLACE TRIGGER  "BI_APM_WRM_PLAN" 
  before insert on "APM_WRM_PLAN"               
  for each row  
begin   
    select "APM_WRM_PLAN_SEQ".nextval into :NEW.ID from dual; 
end; 

/
ALTER TRIGGER  "BI_APM_WRM_PLAN" ENABLE
/
