CREATE TABLE TIMESHEET(TIMESHEETID VARCHAR2(25),OWNER NUMBER(6),REQUESTEDON TIMESTAMP,ASSIGNEDTO NUMBER(6),APPROVALPERCENTAGE NUMBER,APPROVEDON TIMESTAMP,FEEDBACK VARCHAR2(1000),APPRECIATION VARCHAR2(1000),APPROVEDBY NUMBER(6),ATTENDANCE NUMBER(6),WORKINGDAYS NUMBER(6),ATTENDENCEUPDATEDBY NUMBER(6),ATTENDENCEUPDATEDON TIMESTAMP,ATTENDENCEREMARK VARCHAR2(1000),ACCOUNTSTATUS VARCHAR2(50),ACCOUNTUPDATEDBY NUMBER(6),ACCOUNTSREMARKS VARCHAR2(2000),ACCOUNTSUPDATEDON TIMESTAMP,ACCOMPLISHMENTS VARCHAR2(2000),LEARNINGS VARCHAR2(2000),CONSTRAINT "PK_TIMESHEETID" PRIMARY KEY("TIMESHEETID") ENABLE,CONSTRAINT "FK_OWNER" FOREIGN KEY("OWNER") REFERENCES USERS("USERID") ON DELETE CASCADE)
CREATE TABLE TIMESHEETINFO(
INFOID NUMBER(10),
TIMESHEETID VARCHAR2(25),
INFOBY NUMBER(6),
INFOADDEDON TIMESTAMP,
INFO VARCHAR2(2000),
INFOTO NUMBER(6),
CONSTRAINT "PK_INFOID" PRIMARY KEY("INFOID") ENABLE,
CONSTRAINT "FK_INFOBY" FOREIGN KEY("INFOBY") REFERENCES USERS("USERID") ON DELETE CASCADE,
CONSTRAINT "FK_INFOTO" FOREIGN KEY("INFOTO") REFERENCES USERS("USERID") ON DELETE CASCADE,
CONSTRAINT "FK_ TIMESHEETID" FOREIGN KEY("TIMESHEETID") REFERENCES TIMESHEET("TIMESHEETID") ON DELETE CASCADE
)
CREATE SEQUENCE   "INFOID_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;