CREATE TABLE  "REIMBURSEMENT_VOUCHERS" 
   (	"RVID" NUMBER NOT NULL ENABLE, 
	"FILENAME" VARCHAR2(250) NOT NULL ENABLE, 
	"REQUESTEDBY" NUMBER NOT NULL ENABLE, 
	"UPLOADEDBY" NUMBER NOT NULL ENABLE, 
	"CREATEDON" TIMESTAMP (6) NOT NULL ENABLE, 
	"MODIFIEDON" TIMESTAMP (6) NOT NULL ENABLE, 
	"STATUS" NUMBER NOT NULL ENABLE, 
	"ASSIGNEDTO" NUMBER NOT NULL ENABLE, 
	"PERIOD" DATE, 
	 CONSTRAINT "REIMBURSEMENTVOUCHERS_PK" PRIMARY KEY ("RVID") ENABLE
   )
/

CREATE SEQUENCE   "REIMBURSEMENTVOUCHERS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER  NOCYCLE
/


CREATE OR REPLACE TRIGGER  "BI_REIMBURSEMENTVOUCHERS" 
  before insert on "REIMBURSEMENT_VOUCHERS"               
  for each row  
begin   
    select "REIMBURSEMENTVOUCHERS_SEQ".nextval into :NEW.RVID from dual; 
end; 

/
ALTER TRIGGER  "BI_REIMBURSEMENTVOUCHERS" ENABLE
/

CREATE TABLE  "REIMBURSEMENT_BILL" 
   (	"BID" NUMBER NOT NULL ENABLE, 
	"FILENAME" VARCHAR2(250) NOT NULL ENABLE, 
	"RVID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "REIMBURSEMENT_BILL_PK" PRIMARY KEY ("BID") ENABLE, 
	 CONSTRAINT "REIMBURSEMENT_BILL_FK" FOREIGN KEY ("RVID")
	  REFERENCES  "REIMBURSEMENT_VOUCHERS" ("RVID") ENABLE
   )
/
 CREATE SEQUENCE   "REIMBURSEMENT_BILL_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER  NOCYCLE
/

CREATE OR REPLACE TRIGGER  "BI_REIMBURSEMENT_BILL" 
  before insert on "REIMBURSEMENT_BILL"               
  for each row  
begin   
    select "REIMBURSEMENT_BILL_SEQ".nextval into :NEW.BID from dual; 
end; 

/
ALTER TRIGGER  "BI_REIMBURSEMENT_BILL" ENABLE
/

CREATE TABLE  "REIMBURSEMENT_COMMENTS" 
   (	"RCID" NUMBER NOT NULL ENABLE, 
	"COMMENTEDBY" NUMBER NOT NULL ENABLE, 
	"COMMENT_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	"COMMENTS" VARCHAR2(4000) NOT NULL ENABLE, 
	"STATUS" NUMBER NOT NULL ENABLE, 
	"COMMENTEDTO" NUMBER NOT NULL ENABLE, 
	"RVID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "REIMBURSEMENT_COMMENTS_PK" PRIMARY KEY ("RCID") ENABLE, 
	 CONSTRAINT "REIMBURSEMENT_COMMENTS_FK" FOREIGN KEY ("RVID")
	  REFERENCES  "REIMBURSEMENT_VOUCHERS" ("RVID") ENABLE
   )
/
CREATE SEQUENCE   "REIMBURSEMENT_COMMENTS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE
/
CREATE OR REPLACE TRIGGER  "BI_REIMBURSEMENT_COMMENTS" 
  before insert on "REIMBURSEMENT_COMMENTS"               
  for each row  
begin   
    select "REIMBURSEMENT_COMMENTS_SEQ".nextval into :NEW.RCID from dual; 
end; 

/
ALTER TRIGGER  "BI_REIMBURSEMENT_COMMENTS" ENABLE
/