CREATE TABLE  "APM_COMPONENT" 
   (	"COMPONENT_ID" NUMBER NOT NULL ENABLE, 
	"COMPONENT_NAME" VARCHAR2(4000), 
	"TEAM_ID" NUMBER, 
	 CONSTRAINT "APM_COMPONENT_PK" PRIMARY KEY ("COMPONENT_ID") ENABLE, 
	 CONSTRAINT "APM_COMPONENT_CON" UNIQUE ("COMPONENT_NAME") ENABLE, 
	 CONSTRAINT "APM_COMPONENT_FK" FOREIGN KEY ("TEAM_ID")
	  REFERENCES  "APM_TEAM" ("TEAM_ID") ENABLE
   )
/

CREATE OR REPLACE TRIGGER  "BI_APM_COMPONENT" 
  before insert on "APM_COMPONENT"               
  for each row  
begin   
    select "APM_COMPONENT_SEQ".nextval into :NEW.COMPONENT_ID from dual; 
end; 

/
ALTER TRIGGER  "BI_APM_COMPONENT" ENABLE
/

 CREATE SEQUENCE   "APM_COMPONENT_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE
/
CREATE TABLE  "APM_COMPONENT_ISSUES" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"ISSUE_ID" VARCHAR2(35) NOT NULL ENABLE, 
	"COMPONENT_ID" NUMBER, 
	 CONSTRAINT "APM_COMPONENT_ISSUES_PK" PRIMARY KEY ("ID") ENABLE, 
	 CONSTRAINT "APM_COMPONENT_ISSUES_FK" FOREIGN KEY ("COMPONENT_ID")
	  REFERENCES  "APM_COMPONENT" ("COMPONENT_ID") ENABLE
   )
/


CREATE OR REPLACE TRIGGER  "BI_APM_COMPONENT_ISSUES" 
  before insert on "APM_COMPONENT_ISSUES"               
  for each row  
begin   
    select "APM_COMPONENT_ISSUES_SEQ1".nextval into :NEW.ID from dual; 
end; 

/
ALTER TRIGGER  "BI_APM_COMPONENT_ISSUES" ENABLE
/

CREATE SEQUENCE   "APM_COMPONENT_ISSUES_SEQ1"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE
/
