CREATE TABLE APM_PROJECTALERTS(
SLNO NUMBER NOT NULL,
PROJECT NUMBER NOT NULL,
MANAGER NUMBER NOT NULL,
ALERT VARCHAR2(10) NOT NULL,
CONSTRAINT "SLNO_PK"  PRIMARY KEY("SLNO") ENABLE,
CONSTRAINT "PROJECT_FK" FOREIGN KEY ("PROJECT") REFERENCES PROJECT("PID") ON DELETE CASCADE ENABLE,
CONSTRAINT "MANAGER_FK" FOREIGN KEY("MANAGER") REFERENCES USERS("USERID") ON DELETE CASCADE ENABLE
);
CREATE SEQUENCE   "EMAILALERT_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE