package com.eminent.issue;
// Generated Dec 12, 2009 11:06:39 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Fileattach generated by hbm2java
 */
public class Fileattach  implements java.io.Serializable {


     private BigDecimal fileid;
     private Issue issue;
     private String filename;
     private Date attacheddate;
     private BigDecimal owner;
     private String issuestatus;

    public Fileattach() {
    }

	
    public Fileattach(BigDecimal fileid) {
        this.fileid = fileid;
    }
    public Fileattach(BigDecimal fileid, Issue issue, String filename, Date attacheddate, BigDecimal owner, String issuestatus) {
       this.fileid = fileid;
       this.issue = issue;
       this.filename = filename;
       this.attacheddate = attacheddate;
       this.owner = owner;
       this.issuestatus = issuestatus;
    }
   
    public BigDecimal getFileid() {
        return this.fileid;
    }
    
    public void setFileid(BigDecimal fileid) {
        this.fileid = fileid;
    }
    public Issue getIssue() {
        return this.issue;
    }
    
    public void setIssue(Issue issue) {
        this.issue = issue;
    }
    public String getFilename() {
        return this.filename;
    }
    
    public void setFilename(String filename) {
        this.filename = filename;
    }
    public Date getAttacheddate() {
        return this.attacheddate;
    }
    
    public void setAttacheddate(Date attacheddate) {
        this.attacheddate = attacheddate;
    }
    public BigDecimal getOwner() {
        return this.owner;
    }
    
    public void setOwner(BigDecimal owner) {
        this.owner = owner;
    }
    public String getIssuestatus() {
        return this.issuestatus;
    }
    
    public void setIssuestatus(String issuestatus) {
        this.issuestatus = issuestatus;
    }




}


