package com.eminent.issue;
// Generated Dec 12, 2009 11:06:39 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import com.eminent.timesheet.Users;

/**
 * Issue generated by hbm2java
 */
public class Issue  implements java.io.Serializable {


     private String issueid;
     private Project projectid;
     private Modules modules;
     private String foundVersion;
     private String type;
     private String severity;
     private String priority;
     private String subject;
     private String description;
     private Users createdby;
     private Date modifiedon;
     private Users assignedto;
     private String comment1;
     private Date createdon;
     private String rootcause;
     private String expectedResult;
     private Date dueDate;
     private String rating;
     private String feedback;
     private String issuestatus;
     private Set issueUpgradations = new HashSet(0);
     private Set issuecommentses = new HashSet(0);
     private Set fileattachs = new HashSet(0);
     private Set issueSupports = new HashSet(0);
     private Set issueImplementations = new HashSet(0);

    public Issue() {
    }

	
    public Issue(String issueid, Project projectid, Modules modules) {
        this.issueid = issueid;
        this.projectid = projectid;
        this.modules = modules;
    }
    public Issue(String issueid, Project projectid, Modules modules, String foundVersion, String type, String severity, String priority, String subject, String description, Users createdby, Date modifiedon, Users assignedto, String comment1, Date createdon, String rootcause, String expectedResult, Date dueDate, String rating, String feedback, String issuestatus, Set issueUpgradations, Set issuecommentses, Set fileattachs, Set issueSupports, Set issueImplementations) {
       this.issueid = issueid;
       this.projectid = projectid;
       this.modules = modules;
       this.foundVersion = foundVersion;
       this.type = type;
       this.severity = severity;
       this.priority = priority;
       this.subject = subject;
       this.description = description;
       this.createdby = createdby;
       this.modifiedon = modifiedon;
       this.assignedto = assignedto;
       this.comment1 = comment1;
       this.createdon = createdon;
       this.rootcause = rootcause;
       this.expectedResult = expectedResult;
       this.dueDate = dueDate;
       this.rating = rating;
       this.feedback = feedback;
       this.issuestatus = issuestatus;
       this.issueUpgradations = issueUpgradations;
       this.issuecommentses = issuecommentses;
       this.fileattachs = fileattachs;
       this.issueSupports = issueSupports;
       this.issueImplementations = issueImplementations;
    }
   
    public String getIssueid() {
        return this.issueid;
    }
    
    public void setIssueid(String issueid) {
        this.issueid = issueid;
    }
    public Project getProjectid() {
        return this.projectid;
    }
    
    public void setProjectid(Project projectid) {
        this.projectid = projectid;
    }
    public Modules getModules() {
        return this.modules;
    }
    
    public void setModules(Modules modules) {
        this.modules = modules;
    }
    public String getFoundVersion() {
        return this.foundVersion;
    }
    
    public void setFoundVersion(String foundVersion) {
        this.foundVersion = foundVersion;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getSeverity() {
        return this.severity;
    }
    
    public void setSeverity(String severity) {
        this.severity = severity;
    }
    public String getPriority() {
        return this.priority;
    }
    
    public void setPriority(String priority) {
        this.priority = priority;
    }
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public Users getCreatedby() {
        return this.createdby;
    }

    public void setCreatedby(Users createdby) {
        this.createdby = createdby;
    }
    public Date getModifiedon() {
        return this.modifiedon;
    }
    
    public void setModifiedon(Date modifiedon) {
        this.modifiedon = modifiedon;
    }
    public Users getAssignedto() {
        return this.assignedto;
    }
    
    public void setAssignedto(Users assignedto) {
        this.assignedto = assignedto;
    }
    public String getComment1() {
        return this.comment1;
    }
    
    public void setComment1(String comment1) {
        this.comment1 = comment1;
    }
    public Date getCreatedon() {
        return this.createdon;
    }
    
    public void setCreatedon(Date createdon) {
        this.createdon = createdon;
    }
    public String getRootcause() {
        return this.rootcause;
    }
    
    public void setRootcause(String rootcause) {
        this.rootcause = rootcause;
    }
    public String getExpectedResult() {
        return this.expectedResult;
    }
    
    public void setExpectedResult(String expectedResult) {
        this.expectedResult = expectedResult;
    }
    public Date getDueDate() {
        return this.dueDate;
    }
    
    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }
    public String getRating() {
        return this.rating;
    }
    
    public void setRating(String rating) {
        this.rating = rating;
    }
    public String getFeedback() {
        return this.feedback;
    }
    
    public void setFeedback(String feedback) {
        this.feedback = feedback;
    }
    public String getIssuestatus() {
        return this.issuestatus;
    }
    
    public void setIssuestatus(String issuestatus) {
        this.issuestatus = issuestatus;
    }
    public Set getIssueUpgradations() {
        return this.issueUpgradations;
    }
    
    public void setIssueUpgradations(Set issueUpgradations) {
        this.issueUpgradations = issueUpgradations;
    }
    public Set getIssuecommentses() {
        return this.issuecommentses;
    }
    
    public void setIssuecommentses(Set issuecommentses) {
        this.issuecommentses = issuecommentses;
    }
    public Set getFileattachs() {
        return this.fileattachs;
    }
    
    public void setFileattachs(Set fileattachs) {
        this.fileattachs = fileattachs;
    }
    public Set getIssueSupports() {
        return this.issueSupports;
    }
    
    public void setIssueSupports(Set issueSupports) {
        this.issueSupports = issueSupports;
    }
    public Set getIssueImplementations() {
        return this.issueImplementations;
    }
    
    public void setIssueImplementations(Set issueImplementations) {
        this.issueImplementations = issueImplementations;
    }




}


