package com.eminent.issue;
// Generated Dec 12, 2009 11:06:39 AM by Hibernate Tools 3.2.1.GA



/**
 * IssueImplementation generated by hbm2java
 */
public class IssueImplementation  implements java.io.Serializable {


     private String issueid;
     private Issue issue;
     private String projecttype;
     private String phase;
     private String subphase;
     private String subsubphase;
     private String subsubsubphase;

    public IssueImplementation() {
    }
    public IssueImplementation(String issueid) {
        this.issueid = issueid;
   
    }
    public IssueImplementation(String issueid, Issue issue) {
        this.issueid = issueid;
        this.issue = issue;
    }
    public IssueImplementation(String issueid, Issue issue, String projecttype, String phase, String subphase, String subsubphase, String subsubsubphase) {
       this.issueid = issueid;
       this.issue = issue;
       this.projecttype = projecttype;
       this.phase = phase;
       this.subphase = subphase;
       this.subsubphase = subsubphase;
       this.subsubsubphase = subsubsubphase;
    }
   
    public String getIssueid() {
        return this.issueid;
    }
    
    public void setIssueid(String issueid) {
        this.issueid = issueid;
    }
    public Issue getIssue() {
        return this.issue;
    }
    
    public void setIssue(Issue issue) {
        this.issue = issue;
    }
    public String getProjecttype() {
        return this.projecttype;
    }
    
    public void setProjecttype(String projecttype) {
        this.projecttype = projecttype;
    }
    public String getPhase() {
        return this.phase;
    }
    
    public void setPhase(String phase) {
        this.phase = phase;
    }
    public String getSubphase() {
        return this.subphase;
    }
    
    public void setSubphase(String subphase) {
        this.subphase = subphase;
    }
    public String getSubsubphase() {
        return this.subsubphase;
    }
    
    public void setSubsubphase(String subsubphase) {
        this.subsubphase = subsubphase;
    }
    public String getSubsubsubphase() {
        return this.subsubsubphase;
    }
    
    public void setSubsubsubphase(String subsubsubphase) {
        this.subsubsubphase = subsubsubphase;
    }




}


