package com.eminent.issue;
// Generated Dec 12, 2009 11:06:39 AM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Project generated by hbm2java
 */
public class Project implements java.io.Serializable {

    private BigDecimal pid;
    private String version;
    private String pname;
    private String pmanager;
    private String platform;
    private String customer;
    private String category;
    private Date startdate;
    private Date enddate;
    private String projectstatus;
    private String totalhours;
    private String showDetails;
    private String phase;
    private String projectDomain;
    private Set moduleses = new HashSet(0);
    private Set issues = new HashSet(0);
  
    public Project() {
    }

    public Project(BigDecimal pid) {
        this.pid = pid;
    }

    public Project(BigDecimal pid, String pname, String pmanager, String platform, String customer, String category, Date startdate, Date enddate, String projectstatus, String totalhours, String phase, String showDetails,String projectDomain,Set moduleses, Set issues) {
        this.pid = pid;
        this.pname = pname;
        this.pmanager = pmanager;
        this.platform = platform;
        this.customer = customer;
        this.category = category;
        this.startdate = startdate;
        this.enddate = enddate;
        this.projectstatus = projectstatus;
        this.totalhours = totalhours;
        this.phase = phase;
         this.showDetails=showDetails;
        this.projectDomain=projectDomain;
        this.moduleses = moduleses;
        this.issues = issues;
       }

    public BigDecimal getPid() {
        return this.pid;
    }

    public void setPid(BigDecimal pid) {
        this.pid = pid;
    }

    public String getVersion() {
        return this.version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    public String getPname() {
        return this.pname;
    }

    public void setPname(String pname) {
        this.pname = pname;
    }

    public String getPmanager() {
        return this.pmanager;
    }

    public void setPmanager(String pmanager) {
        this.pmanager = pmanager;
    }

    public String getPlatform() {
        return this.platform;
    }

    public void setPlatform(String platform) {
        this.platform = platform;
    }

    public String getCustomer() {
        return this.customer;
    }

    public void setCustomer(String customer) {
        this.customer = customer;
    }

    public String getCategory() {
        return this.category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public Date getStartdate() {
        return this.startdate;
    }

    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    public Date getEnddate() {
        return this.enddate;
    }

    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    public String getProjectstatus() {
        return this.projectstatus;
    }

    public void setProjectstatus(String status) {
        this.projectstatus = status;
    }

    public String getTotalhours() {
        return this.totalhours;
    }

    public void setTotalhours(String totalhours) {
        this.totalhours = totalhours;
    }

    public String getPhase() {
        return this.phase;
    }

    public void setPhase(String phase) {
        this.phase = phase;
    }

    public Set getModuleses() {
        return this.moduleses;
    }

    public void setModuleses(Set moduleses) {
        this.moduleses = moduleses;
    }

    public Set getIssues() {
        return this.issues;
    }

    public void setIssues(Set issues) {
        this.issues = issues;
    }

    public String getShowDetails() {
        return showDetails;
    }

    public void setShowDetails(String showDetails) {
        this.showDetails = showDetails;
    }
    public String getProjectDomain() {
        return projectDomain;
    }

    public void setProjectDomain(String projectDomain) {
        this.projectDomain = projectDomain;
    }

}
