package com.eminent.bpm;
// Generated Jun 14, 2012 4:44:57 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;




/**
 * BpmMainProcess generated by hbm2java
 */
public class BpmMainProcess  implements java.io.Serializable {


    private Integer mpId;
     private String mainProcess;
     private String mpType;
     private Integer bpId;
     private Integer createdby;
     private Date createdon;

    public BpmMainProcess() {
    }

    public BpmMainProcess(Integer mpId, String mainProcess, String mpType, Integer bpId, Integer createdby, Date createdon) {
       this.mpId = mpId;
       this.mainProcess = mainProcess;
       this.mpType  =   mpType;
       this.bpId = bpId;
       this.createdby = createdby;
       this.createdon = createdon;
    }
   
    public Integer getMpId() {
        return this.mpId;
    }
    
    public void setMpId(Integer mpId) {
        this.mpId = mpId;
    }
    public String getMainProcess() {
        return this.mainProcess;
    }
    
    public void setMainProcess(String mainProcess) {
        this.mainProcess = mainProcess;
    }
    public String getMpType() {
        return this.mpType;
    }
    
    public void setMpType(String mpType) {
        this.mpType = mpType;
    }
    public Integer getBpId() {
        return this.bpId;
    }
    
    public void setBpId(Integer bpId) {
        this.bpId = bpId;
    }
    public Integer getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(Integer createdby) {
        this.createdby = createdby;
    }
    public Date getCreatedon() {
        return this.createdon;
    }
    
    public void setCreatedon(Date createdon) {
        this.createdon = createdon;
    }





}


