package com.eminent.bpm;
// Generated Jun 14, 2012 4:44:57 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * BpmSubProcess generated by hbm2java
 */
public class BpmSubProcess  implements java.io.Serializable {


    

     private Integer spId;
     private String subProcess;
     private String spType;
     private Integer mpId;
     private Integer createdby;
     private Date createdon;

    public BpmSubProcess() {
    }

    public BpmSubProcess(Integer spId, String subProcess, String spType, Integer mpId, Integer createdby, Date createdon) {
       this.spId = spId;
       this.subProcess = subProcess;
       this.spType= spType;
       this.mpId = mpId;
       this.createdby = createdby;
       this.createdon = createdon;
    }
   
    public Integer getSpId() {
        return this.spId;
    }
    
    public void setSpId(Integer spId) {
        this.spId = spId;
    }
    public String getSubProcess() {
        return this.subProcess;
    }
    
    public void setSubProcess(String subProcess) {
        this.subProcess = subProcess;
    }
    public String getSpType() {
        return this.spType;
    }
    
    public void setSpType(String spType) {
        this.spType = spType;
    }
    public Integer getMpId() {
        return this.mpId;
    }
    
    public void setMpId(Integer mpId) {
        this.mpId = mpId;
    }
    public Integer getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(Integer createdby) {
        this.createdby = createdby;
    }
    public Date getCreatedon() {
        return this.createdon;
    }
    
    public void setCreatedon(Date createdon) {
        this.createdon = createdon;
    }




}


