package com.eminent.bpm;
// Generated Jul 3, 2012 11:31:18 AM by Hibernate Tools 3.2.1.GA
import java.util.Date;


/**
 * BpmTestscript generated by hbm2java
 */

public class BpmTestscript  implements java.io.Serializable {

     private Integer testscriptId;
     private String testScript;
     private String expectedResult;
     private Integer teststepId;
     private Integer createdby;
     private Date createdon;
     private String ptcid;

    public BpmTestscript() {
    }

    public BpmTestscript(Integer testscriptId, String testScript, String expectedResult, Integer teststepId, Integer createdby, Date createdon, String ptcid) {
       this.testscriptId = testscriptId;
       this.testScript = testScript;
       this.expectedResult = expectedResult;
       this.teststepId = teststepId;
       this.createdby = createdby;
       this.createdon = createdon;
       this.ptcid = ptcid;
    }
   
    public Integer getTestscriptId() {
        return this.testscriptId;
    }
    
    public void setTestscriptId(Integer testscriptId) {
        this.testscriptId = testscriptId;
    }
    public String getTestScript() {
        return this.testScript;
    }
    
    public void setTestScript(String testScript) {
        this.testScript = testScript;
    }
    public String getExpectedResult() {
        return this.expectedResult;
    }
    
    public void setExpectedResult(String expectedResult) {
        this.expectedResult = expectedResult;
    }
    public Integer getTeststepId() {
        return this.teststepId;
    }
    
    public void setTeststepId(Integer teststepId) {
        this.teststepId = teststepId;
    }
    public Integer getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(Integer createdby) {
        this.createdby = createdby;
    }
    public Date getCreatedon() {
        return this.createdon;
    }
    
    public void setCreatedon(Date createdon) {
        this.createdon = createdon;
    }
    public String getPtcid() {
        return this.ptcid;
    }
    
    public void setPtcid(String ptcid) {
        this.ptcid = ptcid;
    }

}


