package com.eminent.bpm;
// Generated Jun 14, 2012 4:44:57 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;




/**
 * BpmTestcase generated by hbm2java
 */
public class BpmTestcase  implements java.io.Serializable {


     private Integer testcaseId;
     private String testcase;
     private String tcType;
     private Integer variantId;
     private String type;
     private String classification;
     private String leadModule;
     private String priority;
     private Integer createdby;
     private Date createdon;

    public BpmTestcase() {
    }

    public BpmTestcase(Integer testcaseId, String testcase, String tcType, Integer variantId, String type, String classification, String leadModule, String priority, Integer createdby, Date createdon) {
       this.testcaseId = testcaseId;
       this.testcase = testcase;
       this.tcType  = tcType;
       this.variantId = variantId;
       this.type = type;
       this.classification = classification;
       this.leadModule = leadModule;
       this.priority = priority;
       this.createdby = createdby;
       this.createdon = createdon;
    }
   
    public Integer getTestcaseId() {
        return this.testcaseId;
    }
    
    public void setTestcaseId(Integer testcaseId) {
        this.testcaseId = testcaseId;
    }
    public String getTestcase() {
        return this.testcase;
    }
    
    public void setTestcase(String testcase) {
        this.testcase = testcase;
    }
        public String getTcType() {
        return this.tcType;
    }
    
    public void setTcType(String tcType) {
        this.tcType = tcType;
    }
    public Integer getVariantId() {
        return this.variantId;
    }
    
    public void setVariantId(Integer variantId) {
        this.variantId = variantId;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getClassification() {
        return this.classification;
    }
    
    public void setClassification(String classification) {
        this.classification = classification;
    }
    public String getLeadModule() {
        return this.leadModule;
    }
    
    public void setLeadModule(String leadModule) {
        this.leadModule = leadModule;
    }
    public String getPriority() {
        return this.priority;
    }
    
    public void setPriority(String priority) {
        this.priority = priority;
    }
    public Integer getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(Integer createdby) {
        this.createdby = createdby;
    }
    public Date getCreatedon() {
        return this.createdon;
    }
    
    public void setCreatedon(Date createdon) {
        this.createdon = createdon;
    }




}


